resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: neon-operator
  newTag: latest
- name: controlplane
  newName: neon-controlplane
  newTag: latest
